# Generated by Django 3.2.7 on 2023-03-03 22:28

import blog.models
from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', blog.models.ParagraphBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(template='blog/blocks/blog_image.html'))]),
        ),
    ]
